blank_issues_enabled: false
contact_links:
  - name: '❓ Discussion Board'
    url: https://github.com/bilbilak/terraform-provider-stalwart-mail/discussions/categories/q-a
    about: Ask your questions here
  - name: '📢 Support Policy'
    url: https://github.com/bilbilak/terraform-provider-stalwart-mail/blob/main/docs/SUPPORT.md
    about: Learn how to get help here
